{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"level":"error","message":"Database connection failed: Access denied for user 'root'@'localhost' (using password: NO)","service":"swiftpos-api","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at Packet.asError (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packets/packet.js:740:17)\n    at ClientHandshake.execute (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/commands/command.js:29:26)\n    at PoolConnection.handlePacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:475:34)\n    at PacketParser.onPacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:93:12)\n    at PacketParser.executeStart (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:100:25)\n    at Socket.emit (node:events:520:28)\n    at Socket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)","timestamp":"2025-08-27 20:15:59"}
{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"level":"error","message":"Database connection failed: Access denied for user 'root'@'localhost' (using password: NO)","service":"swiftpos-api","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at Packet.asError (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packets/packet.js:740:17)\n    at ClientHandshake.execute (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/commands/command.js:29:26)\n    at PoolConnection.handlePacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:475:34)\n    at PacketParser.onPacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:93:12)\n    at PacketParser.executeStart (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:100:25)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)","timestamp":"2025-08-27 20:16:29"}
{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"level":"error","message":"Database connection failed: Access denied for user 'root'@'localhost' (using password: NO)","service":"swiftpos-api","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)","sqlState":"28000","stack":"Error: Access denied for user 'root'@'localhost' (using password: NO)\n    at Packet.asError (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packets/packet.js:740:17)\n    at ClientHandshake.execute (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/commands/command.js:29:26)\n    at PoolConnection.handlePacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:475:34)\n    at PacketParser.onPacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:93:12)\n    at PacketParser.executeStart (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:100:25)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)","timestamp":"2025-08-27 20:17:38"}
{"code":"ER_BAD_DB_ERROR","errno":1049,"level":"error","message":"Database connection failed: Unknown database 'swiftpos'","service":"swiftpos-api","sqlMessage":"Unknown database 'swiftpos'","sqlState":"42000","stack":"Error: Unknown database 'swiftpos'\n    at Packet.asError (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packets/packet.js:740:17)\n    at ClientHandshake.execute (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/commands/command.js:29:26)\n    at PoolConnection.handlePacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:475:34)\n    at PacketParser.onPacket (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:93:12)\n    at PacketParser.executeStart (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/Users/harshil/Desktop/SwiftPOS/backend/node_modules/mysql2/lib/base/connection.js:100:25)\n    at Socket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)","timestamp":"2025-08-27 20:17:58"}
{"address":"::","code":"EADDRINUSE","errno":-48,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"swiftpos-api","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1898:16)\n    at listenInCluster (node:net:1946:12)\n    at Server.listen (node:net:2044:7)\n    at startServer (/Users/harshil/Desktop/SwiftPOS/backend/dist/server.js:141:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"listen","timestamp":"2025-08-27 20:18:26"}
{"address":"::","code":"EADDRINUSE","errno":-48,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"swiftpos-api","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1898:16)\n    at listenInCluster (node:net:1946:12)\n    at Server.listen (node:net:2044:7)\n    at startServer (/Users/harshil/Desktop/SwiftPOS/backend/dist/server.js:141:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"listen","timestamp":"2025-08-27 20:18:54"}
{"address":"::","code":"EADDRINUSE","errno":-48,"level":"error","message":"Uncaught Exception: listen EADDRINUSE: address already in use :::5000","port":5000,"service":"swiftpos-api","stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1898:16)\n    at listenInCluster (node:net:1946:12)\n    at Server.listen (node:net:2044:7)\n    at startServer (/Users/harshil/Desktop/SwiftPOS/backend/dist/server.js:141:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","syscall":"listen","timestamp":"2025-08-27 20:19:06"}
